services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./etc/dashboards:/etc/dashboards
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource, volkovlabs-variable-panel, marcusolsson-dynamictext-panel
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_PLUGINS_PLUGIN_ADMIN_ENABLED: true
      GF_PUBLIC_DASHBOARDS_ENABLED: false
volumes:
  grafana-storage: {}